name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["master"]

env:
  AZURE_FUNCTIONAPP_NAME: 'groomer-backend-services'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'dotnet-sms-service'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    
    - name: 'Fetch Secrets from Key Vault'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          SMS_API_TOKEN=$(az keyvault secret show --name "SmsApiToken" --vault-name ${{ env.AZURE_KEYVAULT_NAME }} --query value -o tsv)
          GROOMER_BACKEND_API_KEY=$(az keyvault secret show --name "GroomerBackendApiKey" --vault-name ${{ env.AZURE_KEYVAULT_NAME }} --query value -o tsv)

          az functionapp config appsettings set 
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} 
            --settings 
              "SmsApi:SmsApiToken=$SMS_API_TOKEN" 
              "ApiSettings:ApiKey=$GROOMER_BACKEND_API_KEY"

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}